const NUMPAD_DIGITS = [1, 2, 3, 4, 5, 6, 7, 8, 9];
const LATENCY_IN_MILLISECONDS = 1000;
const START_TEST_WITH_DIGIT = 3;
const END_TEST_WITH_DIGIT = 5;

export { NUMPAD_DIGITS, LATENCY_IN_MILLISECONDS, START_TEST_WITH_DIGIT, END_TEST_WITH_DIGIT };
